theme: jekyll-theme-minimal
title: 'Artificial Intelligence and Machine Learning - Unit 2'
description: '<b><p style="text-align:left">AA 2025/2026</p></b>'
logo: /imgs/sapienza_logo.png
show_downloads: false
