name: Contributors
on:
  push:
    branches:
      - main
jobs:
  contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/contributors-list@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          userNameHeight: 19
          avatarSize: 64
          avatarMargin: 10
          excludeUsers: Pikarz PhilHippo SchulzKilian leozzzoo zoematr gabrimatx veronicadign RoxyDiya cristinalakasz luigi-pizza rubenciranni Leonard013 Loriv3 Andrea-Salinetti eelse0 tommdim
          svgPath: CONTRIBUTORS_AA2324.svg
          itemTemplate: >
            <g transform="translate({{ x }}, {{ y }})">
              <a xlink:href="{{{ url }}}" class="contributor-link" target="_blank" rel="nofollow sponsored" title="{{{ name }}}" id="{{{ name }}}">
                <image width="{{ width }}" height="{{ height }}" xlink:href="{{{ avatar }}}" />
                <text x="32" y="74" text-anchor="middle" alignment-baseline="middle" font-size="10">{{{ name }}}</text>
              </a>
            </g>
            
